version: "3.9"

services:
  backend:
    build: ./express-backend
    env_file: .env.stage
    ports:
      - "8080:8080"
    restart: always
    networks:
      - safeballot-network
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    depends_on:
      - backend
    volumes:
      - frontend-build:/app/build
    networks:
      - safeballot-network
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=${REACT_APP_API_URL}

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - frontend-build:/usr/share/nginx/html:ro
      - ./nginx.stage.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    networks:
      - safeballot-network

networks:
  safeballot-network:
    driver: bridge

volumes:
  frontend-build:
